### ISSUE TITLE
Extra column to sum times with same task

### ISSUE THREAD

**Issue by jgumesheimer** [tausendstelLicht/zeit-buchung#14]
sometimes tasks get interrupted by other tasks.
If I start and stop everything properly I still have to lump the times of the interrupted tasks together in my head.

Maybe an additional column in the report could do this for me.
As criteria, I would suggest the message (If the message is the same, sum the times together)
Or a new property "task id", which could be set in the start and stop command.

**Comment by tausendstelLicht** [comment]
It's already possible to sum records with the same message by using the report action option ` -s, --sort Records will be sorted by messages.`. But it is useful to have a task id, which will be used as sort criterium. Then it will be possible to write different messages for the same task.

**Comment by tausendstelLicht** [comment]
New feature was released in [2.2.0](https://github.com/tausendstelLicht/zeit-buchung/releases/tag/2.2.0)
